import 'dayjs/locale/en';
import type { FluentTemplate } from './type';

const en_US: FluentTemplate = {
  home: 'Home',
  categories: 'Categories',
  collections: 'Collections',
  profile: 'Profile',

  'top-selling': 'Top Selling',
  'units-sold': '{ $count } sold',
  'see-all': 'See All',
  'latest-products': 'Latest Products',
  'trending-products': 'Trending Products',
  'sign-in': 'Sign In',
  'sign-in-to-view-your-profile': 'Sign in to view your profile and orders',
  'signing-in': 'Signing in...',
  email: 'Email',
  'enter-your-email': 'Enter your email',
  password: 'Password',
  'enter-your-password': 'Enter your password',
  'dont-have-an-account': "Don't have an account? Register",
  'invalid-credentials': 'Invalid credentials. Please try again.',
  'no-collections-found': 'No collections found',
  cart: 'Cart',
  checkout: 'Checkout',
  'go-home': 'Go Home',
  'you-dont-have-anything-in-your-cart':
    "You don't have anything in your cart.\nUse the link below to start below to start browsing our products.",
  'profile-information': 'Profile Information',
  'order-with-id': 'Order # { $id }',
  orders: 'Orders',
  'shipping-addresses': 'Shipping Addresses',
  logout: 'Logout',
  'profile-details': 'Profile Details',
  name: 'Name',
  phone: 'Phone',
  'edit-profile': 'Edit Profile',
  save: 'Save',
  cancel: 'Cancel',
  'first-name': 'First Name',
  'last-name': 'Last Name',
  'no-orders-found': 'No orders found',
  'sign-in-to-view-orders': 'Please sign in to view your orders',
  view: 'View',
  'remaining-items': '{ $count } more',
  'no-categories-found': 'No categories found',
  'browse-by-category': 'Browse by category',
  'categories-subtitle': 'Find products grouped by type',
  'search-categories': 'Search categories',
  'categories-count': '{ $count } categories',
  'subcategories-count': '{ $count } subcategories',
  'no-categories-match': 'No matching categories',
  'try-different-category-search': 'Try a different search term',
  variant: 'Variant',
  'add-a-promo-code': 'Add a Promo Code',
  'enter-promo-code': 'Enter promo code',
  'applied-promotions': 'Applied Promotions',
  'invalid-promo-code': 'Invalid promo code',
  'failed-to-apply-promotion': 'Failed to apply promotion code',
  'failed-to-remove-promotion': 'Failed to remove promotion code',
  apply: 'Apply',
  summary: 'Summary',
  discount: 'Discount',
  subtotal: 'Subtotal',
  shipping: 'Shipping',
  taxes: 'Taxes',
  total: 'Total',
  'use-same-address-for-billing': 'Use same address for billing',
  'shipping-address': 'Shipping Address',
  'billing-address': 'Billing Address',
  address: 'Address',
  company: 'Company',
  optional: 'Optional',
  'postal-code': 'Postal Code',
  city: 'City',
  'province-or-state': 'Province/State',
  country: 'Country',
  'select-a-country': 'Select a country',
  delivery: 'Delivery',
  payment: 'Payment',
  review: 'Review',
  'continue-to-delivery': 'Continue to Delivery',
  'continue-to-payment': 'Continue to Payment',
  'review-order': 'Review Order',
  'pay-using-provider': 'Pay using { $provider }',
  'place-order': 'Place Order',
  continue: 'Continue',
  'please-select-a-payment-method': 'Please select a payment provider',
  'no-cart-found': 'No cart found',
  'payment-provider-not-supported': 'Payment provider not supported',
  'failed-to-complete-order': 'Failed to complete order',
  error: 'Error',
  'an-error-occurred': 'An error occurred',
  'no-cart-id': 'No cart ID',
  'failed-to-update-shipping-method': 'Failed to update shipping method',
  'loading-shipping-options': 'Loading shipping options',
  'select-shipping-method': 'Select Shipping Method',
  calculating: 'Calculating',
  'no-region-id': 'No region ID',
  'stripe-payment-coming-soon': 'Stripe payment UI coming soon!',
  'no-additional-actions-required-for-manual-payment':
    'No additional actions required for manual payment.',
  'payment-provider-is-in-development':
    'Payment provider { $provider } is in development.',
  'loading-payment-options': 'Loading payment options',
  'select-payment-method': 'Select Payment Method',
  qty: 'Qty',
  'shipping-method': 'Shipping Method',
  'payment-method': 'Payment Method',
  'no-shipping-method-selected': 'No shipping method selected',
  'no-shipping-options-available':
    'No shipping options available for this address.',
  'no-payment-method-selected': 'No payment method selected',
  'payment-details': 'Payment Details',
  'manual-payment-instructions':
    'Transfer the order total to the account below. Use your phone number or order reference as the payment reference.',
  'loading-payment-details': 'Loading payment details',
  'no-payment-details-available':
    'Payment account details are not available for this order.',
  'account-holder': 'Account Holder',
  'account-number': 'Account Number',
  'bank-name': 'Bank Name',
  iban: 'IBAN',
  bic: 'BIC / SWIFT',
  'routing-number': 'Routing Number',
  canceled: 'Canceled',
  'not-fulfilled': 'Not Fulfilled',
  'partially-fulfilled': 'Partially Fulfilled',
  fulfilled: 'Fulfilled',
  'partially-shipped': 'Partially Shipped',
  shipped: 'Shipped',
  'partially-delivered': 'Partially Delivered',
  delivered: 'Delivered',
  'count-items': '{ $count } item(s)',
  'order-details': 'Order Details',
  'order-not-found': 'Order not found',
  'placed-on': 'Placed { $datetime }',
  status: 'Status',
  'order-items': 'Order Items',
  contact: 'Contact',
  method: 'Method',
  'order-summary': 'Order Summary',
  'continue-shopping': 'Continue Shopping',
  addresses: 'Addresses',
  'please-sign-in-to-view-your-address':
    'Please sign in to view your addresses',
  'no-addresses-found': 'No addresses found',
  'add-new-address': 'Add New Address',
  'add-address': 'Add Address',
  'edit-address': 'Edit Address',
  'save-changes': 'Save Changes',
  'country-code': 'Country Code',
  'product-information': 'Product Information',
  material: 'Material',
  'country-of-origin': 'Country of origin',
  type: 'Type',
  weight: 'Weight',
  dimensions: 'Dimensions',
  sku: 'SKU',
  'hs-code': 'HS Code',
  'mid-code': 'MID Code',
  'days-return': '{ $count } day(s) return',
  'fast-delivery': 'Fast Delivery',
  'add-to-cart': 'Add to cart',
  'out-of-stock': 'Out of stock',
  'view-cart': 'View cart',
  settings: 'Settings',
  language: 'Language',
  'select-language': 'Select language',
  'language-is-required': 'Language is required',
  'first-name-is-required': 'First name is required',
  'last-name-is-required': 'Last name is required',
  'address-is-required': 'Address is required',
  'postal-code-is-required': 'Postal code is required',
  'city-is-required': 'City is required',
  'country-is-required': 'Country is required',
  'phone-is-required': 'Phone is required',
  'enter-your-phone': 'Enter your phone number',
  'invalid-phone-number': 'Please enter a valid phone number',
  'please-enter-a-valid-email': 'Please enter a valid email',
  'invalid-email-address': 'Invalid email address',
  'password-must-be-at-least-n-characters':
    'Password must be at least { $n } characters',
  register: 'Register',
  'enter-your-first-name': 'Enter your first name',
  'enter-your-last-name': 'Enter your last name',
  'create-account': 'Create Account',
  'creating-account': 'Creating account',
  'already-have-an-account': 'Already have an account? Sign In',
  'registration-failed': 'Registration failed. Please try again.',
  search: 'Search',
  'search-products': 'Search products',
  'type-to-search-products': 'Type at least 2 characters to search products.',
  'search-is-not-configured': 'Search is not configured',
  'add-algolia-credentials-to-search':
    'Add Algolia credentials to your environment to enable product search.',
  'search-failed': 'Search failed',
  'try-searching-again': 'Please try searching again.',
  'no-products-found': 'No products found',
  'try-a-different-search-term': 'Try a different search term.',
  'buy-now': 'Buy Now',
  'official-store': 'Official Store',
  seller: 'Seller',
  'seller-phone': 'Phone',
  'seller-email': 'Email',
  'contact-not-available': 'Contact not available',
  'liked-products': 'Liked Products',
  'no-liked-products': 'No liked products yet',
  'tap-heart-to-save-products':
    'Tap the heart on any product to save it here.',
  'estimated-arrival': 'Estimated Arrival',
  'ships-from-country': 'Ships from { $country }',
  'delivery-estimate-days': 'Estimated delivery: { $days } business days',
  'same-day-delivery': 'Same day delivery',
  'china-shipping-note':
    'This item is shipped from China. Delivery may take longer due to international shipping and customs.',
  'local-shipping-note':
    'This item is in stock locally in Tanzania and is delivered the same day.',
  'price-includes-shipping-and-tax':
    'Price includes shipping and tax.',
  'frequently-searched': 'Frequently searched',
  'clear-search-history': 'Clear',
  'sign-in-required-for-checkout':
    'Please sign in to continue checkout.',
  'create-account-to-view-orders':
    'Create an account to view and track your orders.',
  'create-account-to-continue-checkout':
    'Create an account to complete your order and track it afterwards.',
  'sell-on-jumua': 'Sell on Jumua',
  'become-a-seller': 'Become a Seller',
  'become-a-seller-description':
    "Tell us about your business. We'll review your application and notify you once it's approved.",
  'business-name': 'Business Name',
  'enter-your-business-name': 'Enter your business name',
  'business-name-is-required': 'Business name is required',
  'your-name': 'Your Name',
  'enter-your-name': 'Enter your name',
  'name-is-required': 'Name is required',
  'seller-application-submitted': 'Application Submitted',
  'seller-application-submitted-description':
    "We've received your seller application. You'll be able to sign in and start uploading products once it's approved.",
  submitting: 'Submitting...',
  'submit-application': 'Submit Application',
  'seller-sign-in': 'Seller Sign In',
  'dont-have-a-seller-account': "Don't have a seller account? Apply now",
  'seller-dashboard': 'Seller Dashboard',
  'sign-in-to-manage-your-store': 'Sign in to manage your store',
  'upload-product': 'Upload Product',
  'your-products': 'Your Products',
  'no-products-yet': "You haven't uploaded any products yet.",
  'product-title': 'Product Title',
  'product-title-is-required': 'Product title is required',
  'enter-product-title': 'Enter product title',
  description: 'Description',
  'enter-product-description': 'Enter product description',
  'product-photos': 'Product Photos',
  price: 'Price',
  'price-is-required': 'Price is required',
  'invalid-price': 'Enter a valid price',
  'setting-up-shipping': 'Setting up shipping...',
  'uploading-images': 'Uploading images...',
  'creating-product': 'Creating product...',
  'product-submitted': 'Product Submitted',
  'product-submitted-description':
    'Your product was submitted for review. It will appear in the store once approved.',
  ok: 'OK',
  'failed-to-upload-product': 'Failed to upload product. Please try again.',
  'submit-product': 'Submit Product',
  'no-delivery-note':
    'This product ships with "No Delivery" by default (buyer arranges pickup/delivery with you) so you can start selling right away.',
  'base-price': 'Base Price',
  'setting-up-inventory': 'Setting up inventory...',
  'product-options': 'Options',
  'product-options-description':
    'Add options like Color or Size to create variants (e.g. Red, Blue, Green). Leave empty for a single, simple product.',
  'option-name-placeholder': 'e.g. Color',
  'option-values-placeholder': 'e.g. Red, Blue, Green',
  'add-option': 'Add Option',
  'track-inventory': 'Track Inventory',
  'track-inventory-description':
    'Turn on to set how many units you have in stock.',
  quantity: 'Quantity',
  variants: 'Variants',
  'variants-description':
    'Set a price, stock quantity and photo for each combination below.',
  'variant-image': 'Photo',
  'variant-count': '{ $count } variants',
  'add-photo': 'Add Photo',
  'take-photo': 'Take Photo',
  'choose-from-library': 'Choose from Library',
  'back-to-shopping': 'Back to Shopping',
  shop: 'Shop',
  'seller-orders': 'Orders',
  'no-orders-yet-seller': "You haven't received any orders yet.",
  published: 'Published',
  'pending-review': 'Pending Review',
  'category-optional': 'Category (Optional)',
  'select-category': 'Select a category',
  'sku-optional': 'SKU (Optional)',
  'sku-placeholder': 'e.g. TSHIRT-BLU-M',
  edit: 'Edit',
  'edit-product': 'Edit Product',
  'edit-variant': 'Edit Variant',
  'product-info': 'Product Info',
  'tap-a-variant-to-edit-details':
    'Tap a variant to add its SKU, material, dimensions and customs details.',
  'material-optional': 'Material (Optional)',
  'material-placeholder': 'e.g. Cotton',
  'dimensions-optional': 'Dimensions (Optional)',
  width: 'Width',
  length: 'Length',
  height: 'Height',
  'customs-details-optional': 'Customs Details (Optional)',
  'hs-code-optional': 'HS Code (Optional)',
  'mid-code-optional': 'MID Code (Optional)',
  'country-of-origin-help':
    'Defaults to Tanzania (TZ). Change it if this item ships from elsewhere, e.g. CN for China.',
  saving: 'Saving...',
  'product-updated': 'Product Updated',
  'product-updated-description': 'The product details were saved.',
  'variant-updated': 'Variant Updated',
  'variant-updated-description': 'The variant details were saved.',
  'failed-to-save': 'Failed to save. Please try again.',
  'no-category': 'No category',
  'welcome-back': 'Welcome back',
  'pending-fulfillment': 'Pending',
  'recent-revenue': 'Recent sales',
  'quick-actions': 'Quick actions',
  'recent-orders': 'Recent orders',
  'view-all': 'View all',
  'all-orders': 'All',
  'shipped-orders': 'Shipped',
  'no-orders-for-filter': 'No orders match this filter.',
  'fulfillment-actions': 'Fulfillment',
  'unfulfilled-items': 'Items to fulfill',
  'tracking-number-optional': 'Tracking number (optional)',
  'tracking-number-placeholder': 'e.g. TRK123456789',
  'stock-location-required':
    'Set up a stock location before fulfilling orders. Upload a product first to create one automatically.',
  'create-fulfillment': 'Create fulfillment',
  'mark-as-shipped': 'Mark as shipped',
  'mark-as-delivered': 'Mark as delivered',
  fulfillments: 'Fulfillments',
  'packed-at': 'Packed',
  'shipped-at': 'Shipped',
  'delivered-at': 'Delivered',
  tracking: 'Tracking',
  'items-remaining': '{ $count } remaining',
  'complete-order': 'Complete order',
  'fulfillment-created': 'Fulfillment created',
  'fulfillment-created-description':
    'The order items have been packed and are ready to ship.',
  'order-shipped': 'Order shipped',
  'order-shipped-description': 'The customer will be notified that their order is on the way.',
  'order-delivered': 'Order delivered',
  'order-delivered-description': 'This fulfillment has been marked as delivered.',
  'order-completed': 'Order completed',
  'order-completed-description': 'This order is now marked as completed.',
  'nothing-to-ship': 'There is nothing ready to ship for this order.',
  'nothing-to-deliver': 'There is no shipped fulfillment to mark as delivered.',
  'something-went-wrong': 'Something went wrong. Please try again.',
  'order-items-count': '{ $count } items',
};

export default Object.keys(en_US)
  .map(key => `${key} = ${(en_US as any)[key]}`)
  .join('\n');
