import 'dayjs/locale/id';
import type { FluentTemplate } from './type';

const id_ID: FluentTemplate = {
  home: 'Beranda',
  categories: 'Kategori',
  collections: 'Koleksi',
  profile: 'Profil',

  'top-selling': 'Penjualan Teratas',
  'units-sold': '{ $count } terjual',
  'see-all': 'Lihat Semua',
  'latest-products': 'Produk Terbaru',
  'trending-products': 'Produk Tren',
  'sign-in': 'Masuk',
  'sign-in-to-view-your-profile': 'Masuk untuk melihat profil dan pesanan Anda',
  'signing-in': 'Sedang masuk...',
  email: 'Email',
  'enter-your-email': 'Masukkan email Anda',
  password: 'Kata Sandi',
  'enter-your-password': 'Masukkan kata sandi Anda',
  'dont-have-an-account': 'Belum punya akun? Daftar',
  'invalid-credentials': 'Kredensial tidak valid. Silakan coba lagi.',
  'no-collections-found': 'Tidak ada koleksi yang ditemukan',
  cart: 'Keranjang',
  checkout: 'Pembayaran',
  'go-home': 'Kembali ke Beranda',
  'you-dont-have-anything-in-your-cart':
    'Anda tidak memiliki apa pun di keranjang Anda.\nGunakan tautan di bawah ini untuk mulai menjelajahi produk kami.',
  'profile-information': 'Informasi Profil',
  'order-with-id': 'Pesanan # { $id }',
  orders: 'Pesanan',
  'shipping-addresses': 'Alamat Pengiriman',
  logout: 'Keluar',
  'profile-details': 'Detail Profil',
  name: 'Nama',
  phone: 'Telepon',
  'edit-profile': 'Edit Profil',
  save: 'Simpan',
  cancel: 'Batal',
  'first-name': 'Nama Depan',
  'last-name': 'Nama Belakang',
  'no-orders-found': 'Tidak ada pesanan yang ditemukan',
  'sign-in-to-view-orders': 'Silakan masuk untuk melihat pesanan Anda',
  view: 'Lihat',
  'remaining-items': '{ $count } lagi',
  'no-categories-found': 'Tidak ada kategori yang ditemukan',
  'browse-by-category': 'Jelajahi berdasarkan kategori',
  'categories-subtitle': 'Temukan produk berdasarkan jenis',
  'search-categories': 'Cari kategori',
  'categories-count': '{ $count } kategori',
  'subcategories-count': '{ $count } subkategori',
  'no-categories-match': 'Tidak ada kategori yang cocok',
  'try-different-category-search': 'Coba kata pencarian lain',
  variant: 'Varian',
  'add-a-promo-code': 'Tambahkan Kode Promo',
  'enter-promo-code': 'Masukkan kode promo',
  'applied-promotions': 'Promosi yang Diterapkan',
  'invalid-promo-code': 'Kode promo tidak valid',
  'failed-to-apply-promotion': 'Gagal menerapkan kode promo',
  'failed-to-remove-promotion': 'Gagal menghapus kode promo',
  apply: 'Terapkan',
  summary: 'Ringkasan',
  discount: 'Diskon',
  subtotal: 'Subtotal',
  shipping: 'Pengiriman',
  taxes: 'Pajak',
  total: 'Total',
  'use-same-address-for-billing': 'Gunakan alamat yang sama untuk penagihan',
  'shipping-address': 'Alamat Pengiriman',
  'billing-address': 'Alamat Penagihan',
  address: 'Alamat',
  company: 'Perusahaan',
  optional: 'Opsional',
  'postal-code': 'Kode Pos',
  city: 'Kota',
  'province-or-state': 'Provinsi',
  country: 'Negara',
  'select-a-country': 'Pilih negara',
  delivery: 'Pengiriman',
  payment: 'Pembayaran',
  review: 'Tinjauan',
  'continue-to-delivery': 'Lanjutkan ke Pengiriman',
  'continue-to-payment': 'Lanjutkan ke Pembayaran',
  'review-order': 'Tinjau Pesanan',
  'pay-using-provider': 'Bayar menggunakan { $provider }',
  'place-order': 'Lakukan Pemesanan',
  continue: 'Lanjutkan',
  'please-select-a-payment-method': 'Silakan pilih penyedia pembayaran',
  'no-cart-found': 'Keranjang tidak ditemukan',
  'payment-provider-not-supported': 'Penyedia pembayaran tidak didukung',
  'failed-to-complete-order': 'Gagal menyelesaikan pesanan',
  error: 'Kesalahan',
  'an-error-occurred': 'Terjadi kesalahan',
  'no-cart-id': 'ID Keranjang tidak ada',
  'failed-to-update-shipping-method': 'Gagal memperbarui metode pengiriman',
  'loading-shipping-options': 'Memuat opsi pengiriman',
  'select-shipping-method': 'Pilih Metode Pengiriman',
  calculating: 'Menghitung',
  'no-region-id': 'ID wilayah tidak ada',
  'stripe-payment-coming-soon': 'Antarmuka pembayaran Stripe segera hadir!',
  'no-additional-actions-required-for-manual-payment':
    'Tidak ada tindakan tambahan yang diperlukan untuk pembayaran manual.',
  'payment-provider-is-in-development':
    'Penyedia pembayaran { $provider } sedang dalam pengembangan.',
  'loading-payment-options': 'Memuat opsi pembayaran',
  'select-payment-method': 'Pilih Metode Pembayaran',
  qty: 'Jml',
  'shipping-method': 'Metode Pengiriman',
  'payment-method': 'Metode Pembayaran',
  'no-shipping-method-selected': 'Tidak ada metode pengiriman yang dipilih',
  'no-shipping-options-available':
    'Tidak ada opsi pengiriman untuk alamat ini.',
  'no-payment-method-selected': 'Tidak ada metode pembayaran yang dipilih',
  'payment-details': 'Detail Pembayaran',
  'manual-payment-instructions':
    'Transfer total pesanan ke rekening di bawah. Gunakan nomor telepon atau referensi pesanan sebagai keterangan pembayaran.',
  'loading-payment-details': 'Memuat detail pembayaran',
  'no-payment-details-available':
    'Detail rekening pembayaran tidak tersedia untuk pesanan ini.',
  'account-holder': 'Nama Pemilik Rekening',
  'account-number': 'Nomor Rekening',
  'bank-name': 'Nama Bank',
  iban: 'IBAN',
  bic: 'BIC / SWIFT',
  'routing-number': 'Nomor Routing',
  canceled: 'Dibatalkan',
  'not-fulfilled': 'Belum Dipenuhi',
  'partially-fulfilled': 'Sebagian Dipenuhi',
  fulfilled: 'Dipenuhi',
  'partially-shipped': 'Sebagian Dikirim',
  shipped: 'Dikirim',
  'partially-delivered': 'Sebagian Diterima',
  delivered: 'Diterima',
  'count-items': '{ $count } item',
  'order-details': 'Detail Pesanan',
  'order-not-found': 'Pesanan tidak ditemukan',
  'placed-on': 'Dipesan pada { $datetime }',
  status: 'Status',
  'order-items': 'Item Pesanan',
  contact: 'Kontak',
  method: 'Metode',
  'order-summary': 'Ringkasan Pesanan',
  'continue-shopping': 'Lanjutkan Belanja',
  addresses: 'Alamat',
  'please-sign-in-to-view-your-address':
    'Silakan masuk untuk melihat alamat Anda',
  'no-addresses-found': 'Tidak ada alamat yang ditemukan',
  'add-new-address': 'Tambahkan Alamat Baru',
  'add-address': 'Tambahkan Alamat',
  'edit-address': 'Edit Alamat',
  'save-changes': 'Simpan Perubahan',
  'country-code': 'Kode Negara',
  'product-information': 'Informasi Produk',
  material: 'Bahan',
  'country-of-origin': 'Negara Asal',
  type: 'Tipe',
  weight: 'Berat',
  dimensions: 'Dimensi',
  sku: 'SKU',
  'hs-code': 'Kode HS',
  'mid-code': 'Kode MID',
  'days-return': 'Pengembalian dalam { $count } hari',
  'fast-delivery': 'Pengiriman Cepat',
  'add-to-cart': 'Tambahkan ke keranjang',
  'out-of-stock': 'Stok habis',
  'view-cart': 'Lihat keranjang',
  settings: 'Pengaturan',
  language: 'Bahasa',
  'select-language': 'Pilih bahasa',
  'language-is-required': 'Bahasa wajib diisi',
  'first-name-is-required': 'Nama depan wajib diisi',
  'last-name-is-required': 'Nama belakang wajib diisi',
  'address-is-required': 'Alamat wajib diisi',
  'postal-code-is-required': 'Kode pos wajib diisi',
  'city-is-required': 'Kota wajib diisi',
  'country-is-required': 'Negara wajib diisi',
  'phone-is-required': 'Nomor telepon wajib diisi',
  'enter-your-phone': 'Masukkan nomor telepon Anda',
  'invalid-phone-number': 'Silakan masukkan nomor telepon yang valid',
  'please-enter-a-valid-email': 'Silakan masukkan email yang valid',
  'invalid-email-address': 'Alamat email tidak valid',
  'password-must-be-at-least-n-characters':
    'Kata sandi harus terdiri dari setidaknya { $n } karakter',
  register: 'Daftar',
  'enter-your-first-name': 'Masukkan nama depan Anda',
  'enter-your-last-name': 'Masukkan nama belakang Anda',
  'create-account': 'Buat Akun',
  'creating-account': 'Sedang membuat akun',
  'already-have-an-account': 'Sudah memiliki akun? Masuk',
  'registration-failed': 'Pendaftaran gagal. Silakan coba lagi.',
  search: 'Cari',
  'search-products': 'Cari produk',
  'type-to-search-products':
    'Ketik minimal 2 karakter untuk mencari produk.',
  'search-is-not-configured': 'Pencarian belum dikonfigurasi',
  'add-algolia-credentials-to-search':
    'Tambahkan kredensial Algolia ke environment untuk mengaktifkan pencarian produk.',
  'search-failed': 'Pencarian gagal',
  'try-searching-again': 'Silakan coba cari lagi.',
  'no-products-found': 'Produk tidak ditemukan',
  'try-a-different-search-term': 'Coba kata pencarian lain.',
  'buy-now': 'Beli Sekarang',
  'official-store': 'Toko Resmi',
  seller: 'Penjual',
  'seller-phone': 'Telepon',
  'seller-email': 'Email',
  'contact-not-available': 'Kontak tidak tersedia',
  'liked-products': 'Produk Favorit',
  'no-liked-products': 'Belum ada produk favorit',
  'tap-heart-to-save-products':
    'Ketuk ikon hati pada produk untuk menyimpannya di sini.',
  'estimated-arrival': 'Perkiraan Tiba',
  'ships-from-country': 'Dikirim dari { $country }',
  'delivery-estimate-days': 'Perkiraan pengiriman: { $days } hari kerja',
  'same-day-delivery': 'Pengiriman hari yang sama',
  'china-shipping-note':
    'Barang ini dikirim dari China. Pengiriman mungkin lebih lama karena pengiriman internasional dan bea cukai.',
  'local-shipping-note':
    'Barang ini tersedia lokal di Tanzania dan dikirim pada hari yang sama.',
  'price-includes-shipping-and-tax':
    'Harga sudah termasuk ongkos kirim dan pajak.',
  'frequently-searched': 'Pencarian populer',
  'clear-search-history': 'Hapus',
  'sign-in-required-for-checkout':
    'Silakan masuk untuk melanjutkan checkout.',
  'create-account-to-view-orders':
    'Buat akun untuk melihat dan melacak pesanan Anda.',
  'create-account-to-continue-checkout':
    'Buat akun untuk menyelesaikan pesanan Anda dan melacaknya nanti.',
  'sell-on-jumua': 'Jual di Jumua',
  'become-a-seller': 'Menjadi Penjual',
  'become-a-seller-description':
    'Ceritakan tentang bisnis Anda. Kami akan meninjau aplikasi Anda dan memberi tahu Anda setelah disetujui.',
  'business-name': 'Nama Bisnis',
  'enter-your-business-name': 'Masukkan nama bisnis Anda',
  'business-name-is-required': 'Nama bisnis wajib diisi',
  'your-name': 'Nama Anda',
  'enter-your-name': 'Masukkan nama Anda',
  'name-is-required': 'Nama wajib diisi',
  'seller-application-submitted': 'Aplikasi Terkirim',
  'seller-application-submitted-description':
    'Kami telah menerima aplikasi penjual Anda. Anda dapat masuk dan mulai mengunggah produk setelah disetujui.',
  submitting: 'Mengirim...',
  'submit-application': 'Kirim Aplikasi',
  'seller-sign-in': 'Masuk Penjual',
  'dont-have-a-seller-account': 'Belum punya akun penjual? Daftar sekarang',
  'seller-dashboard': 'Dasbor Penjual',
  'sign-in-to-manage-your-store': 'Masuk untuk mengelola toko Anda',
  'upload-product': 'Unggah Produk',
  'your-products': 'Produk Anda',
  'no-products-yet': 'Anda belum mengunggah produk apa pun.',
  'product-title': 'Judul Produk',
  'product-title-is-required': 'Judul produk wajib diisi',
  'enter-product-title': 'Masukkan judul produk',
  description: 'Deskripsi',
  'enter-product-description': 'Masukkan deskripsi produk',
  'product-photos': 'Foto Produk',
  price: 'Harga',
  'price-is-required': 'Harga wajib diisi',
  'invalid-price': 'Masukkan harga yang valid',
  'setting-up-shipping': 'Menyiapkan pengiriman...',
  'uploading-images': 'Mengunggah gambar...',
  'creating-product': 'Membuat produk...',
  'product-submitted': 'Produk Terkirim',
  'product-submitted-description':
    'Produk Anda telah dikirim untuk ditinjau. Produk akan muncul di toko setelah disetujui.',
  ok: 'OK',
  'failed-to-upload-product': 'Gagal mengunggah produk. Silakan coba lagi.',
  'submit-product': 'Kirim Produk',
  'no-delivery-note':
    'Produk ini menggunakan "Tanpa Pengiriman" secara default (pembeli mengatur pengambilan/pengiriman langsung dengan Anda) agar Anda bisa langsung mulai berjualan.',
  'base-price': 'Harga Dasar',
  'setting-up-inventory': 'Menyiapkan stok...',
  'product-options': 'Opsi Produk',
  'product-options-description':
    'Tambahkan opsi seperti Warna atau Ukuran untuk membuat varian (mis. Merah, Biru, Hijau). Biarkan kosong untuk produk sederhana tanpa varian.',
  'option-name-placeholder': 'mis. Warna',
  'option-values-placeholder': 'mis. Merah, Biru, Hijau',
  'add-option': 'Tambah Opsi',
  'track-inventory': 'Lacak Stok',
  'track-inventory-description':
    'Aktifkan untuk mengatur jumlah stok yang Anda miliki.',
  quantity: 'Jumlah',
  variants: 'Varian',
  'variants-description':
    'Atur harga, jumlah stok, dan foto untuk setiap kombinasi di bawah ini.',
  'variant-image': 'Foto',
  'variant-count': '{ $count } varian',
  'add-photo': 'Tambah Foto',
  'take-photo': 'Ambil Foto',
  'choose-from-library': 'Pilih dari Galeri',
  'back-to-shopping': 'Kembali Belanja',
  shop: 'Belanja',
  'seller-orders': 'Pesanan',
  'no-orders-yet-seller': 'Anda belum menerima pesanan apa pun.',
  published: 'Dipublikasikan',
  'pending-review': 'Menunggu Peninjauan',
  'category-optional': 'Kategori (Opsional)',
  'select-category': 'Pilih kategori',
  'sku-optional': 'SKU (Opsional)',
  'sku-placeholder': 'mis. TSHIRT-BLU-M',
  edit: 'Ubah',
  'edit-product': 'Ubah Produk',
  'edit-variant': 'Ubah Varian',
  'product-info': 'Info Produk',
  'tap-a-variant-to-edit-details':
    'Ketuk varian untuk menambahkan SKU, bahan, dimensi, dan detail bea cukai.',
  'material-optional': 'Bahan (Opsional)',
  'material-placeholder': 'mis. Katun',
  'dimensions-optional': 'Dimensi (Opsional)',
  width: 'Lebar',
  length: 'Panjang',
  height: 'Tinggi',
  'customs-details-optional': 'Detail Bea Cukai (Opsional)',
  'hs-code-optional': 'Kode HS (Opsional)',
  'mid-code-optional': 'Kode MID (Opsional)',
  'country-of-origin-help':
    'Default ke Tanzania (TZ). Ubah jika barang ini dikirim dari tempat lain, mis. CN untuk China.',
  saving: 'Menyimpan...',
  'product-updated': 'Produk Diperbarui',
  'product-updated-description': 'Detail produk telah disimpan.',
  'variant-updated': 'Varian Diperbarui',
  'variant-updated-description': 'Detail varian telah disimpan.',
  'failed-to-save': 'Gagal menyimpan. Silakan coba lagi.',
  'no-category': 'Tanpa kategori',
  'welcome-back': 'Selamat datang kembali',
  'pending-fulfillment': 'Menunggu',
  'recent-revenue': 'Penjualan terbaru',
  'quick-actions': 'Tindakan cepat',
  'recent-orders': 'Pesanan terbaru',
  'view-all': 'Lihat semua',
  'all-orders': 'Semua',
  'shipped-orders': 'Dikirim',
  'no-orders-for-filter': 'Tidak ada pesanan untuk filter ini.',
  'fulfillment-actions': 'Pemenuhan',
  'unfulfilled-items': 'Item yang perlu dipenuhi',
  'tracking-number-optional': 'Nomor pelacakan (opsional)',
  'tracking-number-placeholder': 'mis. TRK123456789',
  'stock-location-required':
    'Siapkan lokasi stok sebelum memenuhi pesanan. Unggah produk terlebih dahulu untuk membuatnya otomatis.',
  'create-fulfillment': 'Buat pemenuhan',
  'mark-as-shipped': 'Tandai sudah dikirim',
  'mark-as-delivered': 'Tandai sudah diterima',
  fulfillments: 'Pemenuhan',
  'packed-at': 'Dikemas',
  'shipped-at': 'Dikirim',
  'delivered-at': 'Diterima',
  tracking: 'Pelacakan',
  'items-remaining': '{ $count } tersisa',
  'complete-order': 'Selesaikan pesanan',
  'fulfillment-created': 'Pemenuhan dibuat',
  'fulfillment-created-description':
    'Item pesanan telah dikemas dan siap dikirim.',
  'order-shipped': 'Pesanan dikirim',
  'order-shipped-description': 'Pelanggan akan diberitahu bahwa pesanan mereka sedang dikirim.',
  'order-delivered': 'Pesanan diterima',
  'order-delivered-description': 'Pemenuhan ini telah ditandai sebagai diterima.',
  'order-completed': 'Pesanan selesai',
  'order-completed-description': 'Pesanan ini sekarang ditandai selesai.',
  'nothing-to-ship': 'Tidak ada yang siap dikirim untuk pesanan ini.',
  'nothing-to-deliver': 'Tidak ada pemenuhan yang dikirim untuk ditandai diterima.',
  'something-went-wrong': 'Terjadi kesalahan. Silakan coba lagi.',
  'order-items-count': '{ $count } item',
};

export default Object.keys(id_ID)
  .map(key => `${key} = ${(id_ID as any)[key]}`)
  .join('\n');
